// import all of the images for each team member
import rodrigoAldrey from "../../../img/eboard_photos/rodrigo_aldrey.png";
import pattyKang from "../../../img/eboard_photos/patty_kang.png";
import philipLeung from "../../../img/eboard_photos/philip_leung.png";
import unknownImage from "../../../img/eboard_photos/unknown.png";

export const TeamMember = [
  {
    key: "member1",
    headshot: philipLeung,
    name: "Philip Leung",
    position: "President",
    team: "Executive Team",
    linkedin: "https://www.linkedin.com/in/philipleungg/",
    alt: "",
  },
  {
    key: "member2",
    headshot: unknownImage,
    name: "Arnav Mishra",
    position: "Vice President",
    team: "Executive Team",
    linkedin: "https://www.linkedin.com/in/arnav-mishra-1960001b1/",
    alt: "",
  },
  {
    key: "member3",
    headshot: unknownImage,
    name: "Johnny Garibayatef",
    position: "Scheduling Coordinator",
    team: "Executive Team",
    linkedin: "https://www.linkedin.com/in/juan-garibay-atef/",
    alt: "",
  },
  {
    key: "member4",
    headshot: unknownImage,
    name: "Olivia Yeung",
    position: "Treasurer",
    team: "Executive Team",
    linkedin: "https://www.linkedin.com/in/olivia-yeung/",
    alt: "",
  },
  {
    key: "member5",
    headshot: unknownImage,
    name: "Piya Sarkar",
    position: "Director of Research",
    team: "Reserach Team",
    linkedin: "https://www.linkedin.com/in/piya-sarkar/",
    alt: "",
  },
  {
    key: "member6",
    headshot: unknownImage,
    name: "Wilson Chang",
    position: "Research Associate",
    team: "Research Team",
    linkedin: "https://www.linkedin.com/in/wilson-chang-4744262a4/",
    alt: "",
  },
  {
    key: "member7",
    headshot: rodrigoAldrey,
    name: "Rodrigo Aldrey",
    position: "Director of Tech",
    team: "Tech Team",
    linkedin: "https://www.linkedin.com/in/rodrigo-aldrey-558808244/",
    alt: "",
  },
  {
    key: "member8",
    headshot: unknownImage,
    name: "Cindy Chen",
    position: "Tech Associate",
    team: "Tech Team",
    linkedin: "www.linkedin.com/in/cindy-chen-643ab1287",
    alt: "",
  },
  {
    key: "member9",
    headshot: pattyKang,
    name: "Patty Kang",
    position: "Director of Marketing",
    team: "Marketing Team",
    linkedin: "https://www.linkedin.com/in/peiti-kang-653212250/",
    alt: "",
  },
  {
    key: "member10",
    headshot: unknownImage,
    name: "Pujita Kalinadhabhotla",
    position: "Marketing Associate",
    team: "Marketing Team",
    linkedin: "https://www.linkedin.com/in/pujita-kalinadhabhotla/",
    alt: "",
  },
  {
    key: "member11",
    headshot: unknownImage,
    name: "Erica Zheng",
    position: "Director of Events",
    team: "Events Team",
    linkedin: "https://www.linkedin.com/in/zhengerica/",
    alt: "",
  },
  {
    key: "member12",
    headshot: unknownImage,
    name: "Rich Zou",
    position: "Events Coordinator",
    team: "Events Team",
    linkedin: "https://www.linkedin.com/in/rich-zou/",
    alt: "",
  },
  {
    key: "member13",
    headshot: unknownImage,
    name: "Salmo Elmosallamy",
    position: "Events Coordinator",
    team: "Events Team",
    linkedin: "https://www.linkedin.com/in/aashka-dave/",
    alt: "",
  },
  {
    key: "member14",
    headshot: unknownImage,
    name: "Juliana Kim",
    position: "Events Coordinator",
    team: "Events Team",
    linkedin: "https://www.linkedin.com/in/juliana-kim-52ab6b30b//",
    alt: "",
  },
  {
    key: "member15",
    headshot: unknownImage,
    name: "Gordon Bie",
    position: "Events Coordinator",
    team: "Events Team",
    linkedin: "https://www.linkedin.com/in/gordon-bie/",
    alt: "",
  },
  {
    key: "member16",
    headshot: unknownImage,
    name: "Nicole Schubert",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "https://www.linkedin.com/in/nicole-schubert1/",
    alt: "",
  },
  {
    key: "member17",
    headshot: unknownImage,
    name: "Arnav Sawant",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "https://www.linkedin.com/in/arnav-sawant/",
    alt: "",
  },
  {
    key: "member18",
    headshot: unknownImage,
    name: "Arsh Jafri",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "https://www.linkedin.com/in/arshjafri/",
    alt: "",
  },
  {
    key: "member19",
    headshot: unknownImage,
    name: "Divya Thoppae",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "https://www.linkedin.com/in/divya-thoppae/",
    alt: "",
  },
  {
    key: "member20",
    headshot: unknownImage,
    name: "Abhishek Pujara",
    position: "Director of Quant",
    team: "Quant Team",
    linkedin: "https://www.linkedin.com/in/abhishek-pujara/",
    alt: "",
  },
  {
    key: "member20",
    headshot: unknownImage,
    name: "Cameron Ryan",
    position: "Quant Associate",
    team: "Quant Team",
    linkedin: "https://www.linkedin.com/in/cameron--ryan/",
    alt: "",
  },
  {
    key: "member21",
    headshot: unknownImage,
    name: "Hannah Wimpy",
    position: "Quant Associate",
    team: "Quant Team",
    linkedin: "https://www.linkedin.com/in/hannahgwimpy/",
    alt: "",
  },
  {
    key: "member22",
    headshot: unknownImage,
    name: "Diya Jhamtani",
    position: "Quant Associate",
    team: "Quant Team",
    linkedin: "https://www.linkedin.com/in/diya-jhamtani-a4b763237/",
    alt: "",
  },
  {
    key: "member23",
    headshot: unknownImage,
    name: "Ved Naykude",
    position: "Quant Associate",
    team: "Quant Team",
    linkedin: "https://www.linkedin.com/in/vedn123/",
    alt: "",
  },
  {
    key: "member24",
    headshot: unknownImage,
    name: "Eesha Varma Gottumukkala",
    position: "Director of Consulting",
    team: "Consulting Team",
    linkedin: "https://www.linkedin.com/in/eeshavarma/",
    alt: "",
  },  {
    key: "member25",
    headshot: unknownImage,
    name: "Eshaan Mehta",
    position: "Consulting Associate",
    team: "Consulting Team",
    linkedin: "https://www.linkedin.com/in/eshaantm/",
    alt: "",
  },  {
    key: "member26",
    headshot: unknownImage,
    name: "Ved Naykude",
    position: "Consulting Associate",
    team: "Consulting Team",
    linkedin: "https://www.linkedin.com/in/vedn123/",
    alt: "",
  },

];
