// import all of the images for each team member
import riderBishop from "../../../img/eboard_photos/rider_bishop.jpg";
import yvonneLin from "../../../img/eboard_photos/yvonne_lin.png";
import alexChoi from "../../../img/eboard_photos/alex_choi.png";
import xavierYu from "../../../img/eboard_photos/xavier_yu.png";
import kaamilThobani from "../../../img/eboard_photos/kaamil_thobani.png";
import williamSeward from "../../../img/eboard_photos/william_seward.png";
import rodrigoAldrey from "../../../img/eboard_photos/rodrigo_aldrey.png";
import pattyKang from "../../../img/eboard_photos/patty_kang.png";
import anishSanghi from "../../../img/eboard_photos/anish_sanghi.png";
import alexanderWong from "../../../img/eboard_photos/alexander_wong.png";
import sethMorton from "../../../img/eboard_photos/seth_morton.jpg";
import philipLeung from "../../../img/eboard_photos/philip_leung.png";
import aashkaDave from "../../../img/eboard_photos/aashka_dave.png";
import zainabHussainSyed from "../../../img/eboard_photos/zainab_hussain_syed.png";
import anyaSolanki from "../../../img/eboard_photos/anya_solanki.png";
import aravGoyal from "../../../img/eboard_photos/arav_goyal.png";
import michaelRicardo from "../../../img/eboard_photos/michael_ricardo.png";
import wanruSkuldShao from "../../../img/eboard_photos/wanru_skuld_shao.jpg";
import diyaJhamtani from "../../../img/eboard_photos/diya_jhamtani.png";
import emilyKyne from "../../../img/eboard_photos/emily_kyne.png";
import jackAnderson from "../../../img/eboard_photos/jack_anderson.png";
import justinWee from "../../../img/eboard_photos/justin_wee.png";
import tejChakravarthy from "../../../img/eboard_photos/tej_chakravarthy.png";
import jacobChen from "../../../img/eboard_photos/jacob_chen.png";
import srijithGomattam from "../../../img/eboard_photos/srijith_gomattam.png";
import unknownImage from "../../../img/eboard_photos/unknown.png";

export const TeamMember = [
  {
    key: "member1",
    headshot: riderBishop,
    name: "Rider Bishop",
    position: "President",
    team: "Executive Team",
    linkedin: "https://www.linkedin.com/in/rider-bishop/",
    alt: "",
  },
  {
    key: "member2",
    headshot: philipLeung,
    name: "Philip Leung",
    position: "Vice President",
    team: "Executive Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member3",
    headshot: anishSanghi,
    name: "Anish Sanghi",
    position: "Schedueling Coordinator",
    team: "Executive Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member4",
    headshot: xavierYu,
    name: "Xavier Yu",
    position: "Treasurer",
    team: "Executive Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member5",
    headshot: unknownImage,
    name: "Tarun Anbarasu",
    position: "Director of Research",
    team: "Reserach Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member6",
    headshot: unknownImage,
    name: "Anderson Lo",
    position: "Research Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member7",
    headshot: alexanderWong,
    name: "Alexander Wong",
    position: "Research Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member8",
    headshot: anyaSolanki,
    name: "Anya Solanki",
    position: "Research Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member9",
    headshot: michaelRicardo,
    name: "Michael Ricardo",
    position: "Research Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member10",
    headshot: emilyKyne,
    name: "Emily Kyne",
    position: "Research Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member11",
    headshot: wanruSkuldShao,
    name: "Wanru Shao",
    position: "Research Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member12",
    headshot: unknownImage,
    name: "Svarra Shah",
    position: "Reserach Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member13",
    headshot: srijithGomattam,
    name: "Srijith Gomattam",
    position: "Research Analyst",
    team: "Research Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member14",
    headshot: yvonneLin,
    name: "Yvonne Lin",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member15",
    headshot: unknownImage,
    name: "Aden Levy",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member16",
    headshot: alexChoi,
    name: "Alex Choi",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member17",
    headshot: tejChakravarthy,
    name: "Tej Chakravarthy",
    position: "Co-Director of Finnovate",
    team: "Finnovate Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member18",
    headshot: jackAnderson,
    name: "Jack Anderson",
    position: "Director of Events",
    team: "Events Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member19",
    headshot: aashkaDave,
    name: "Aashka Dave",
    position: "Event Coordinator",
    team: "Events Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member20",
    headshot: zainabHussainSyed,
    name: "Zainab Hussain Syed",
    position: "Event Coordinator",
    team: "Events Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member21",
    headshot: justinWee,
    name: "Justin Wee",
    position: "Collab Event Coordinator",
    team: "Events Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member22",
    headshot: kaamilThobani,
    name: "Kaamil Thobani",
    position: "Director of Technology",
    team: "Technology Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member23",
    headshot: williamSeward,
    name: "William Seward",
    position: "Technology Programer",
    team: "Technology Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member24",
    headshot: unknownImage,
    name: "Arnav Mishra",
    position: "Technology Programmer",
    team: "Technology Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member25",
    headshot: aravGoyal,
    name: "Arav Goyal",
    position: "Technology Programmer",
    team: "Technology Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member26",
    headshot: diyaJhamtani,
    name: "Diya Jhamtani",
    position: "Technology Programmer",
    team: "Technology Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member27",
    headshot: unknownImage,
    name: "Vilasini Nathan",
    position: "Technology Programmer",
    team: "Technology Team",
    linkedin: "https://www.linkedin.com/in/xavier-yu/",
    alt: "",
  },
  {
    key: "member28",
    headshot: rodrigoAldrey,
    name: "Rodrigo Aldrey",
    position: "Co-Director of Marketing",
    team: "Marketing",
    linkedin: "",
    alt: "",
  },
  {
    key: "member29",
    headshot: pattyKang,
    name: "Patty Kang",
    position: "Co-Director of Marketing",
    team: "Marketing Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member30",
    headshot: unknownImage,
    name: "Siya Patel",
    position: "Student Outreach",
    team: "Marketing Team",
    linkedin: "https://www.linkedin.com/",
    alt: "",
  },
  {
    key: "member31",
    headshot: jacobChen,
    name: "Jacob Chen",
    position: "Industry Outreach",
    team: "Marketing Team",
    linkedin: "",
    alt: "",
  },
  {
    key: "member32",
    headshot: sethMorton,
    name: "Seth Morton",
    position: "Director of Engagement",
    team: "Marketing Team",
    linkedin: "https://www.linkedin.com/in/kaamil-thobani-9a7237210/",
    alt: "",
  },
];
