export const WORKSHOP_CARDS = [
  {
    key: "kickoff1",
    header: "Intro to Fintech",
    workshopNum: "1",
    date: "JAN 22 2025",
    startTime: "6:00 PM",
    endTime: "7:00 PM",
  },
  {
    key: "kickoff2",
    header: "Ideation",
    workshopNum: "2",
    date: "JAN 29 2025",
    startTime: "6:00 PM",
    endTime: "8:00 PM",
  },
  {
    key: "workshop1",
    header: "Validating Ideas",
    workshopNum: "3",
    date: "FEB 5 2025",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
  },
  {
    key: "workshop2",
    header: "Business Models",
    workshopNum: "4",
    date: "FEB 12 2025",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
  },
  {
    key: "workshop3",
    header: "Figma",
    workshopNum: "5",
    date: "FEB 19 2025",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
  },
  {
    key: "workshop4",
    header: "Marketing",
    workshopNum: "6",
    date: "FEB 26 2025",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
  },
  {
    key: "workshop5",
    header: "Past Pitches",
    workshopNum: "7",
    date: "MAR 12 2025",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
    topic1: "TBD",
  },
  {
    key: "workshop6",
    header: "How to Pitch",
    workshopNum: "8",
    date: "MAR 19 2025",
    startTime: "6:00 PM",
    endTime: "8:00 PM",
    topic1: "TBD",
  },
  {
    key: "workshop7",
    header: "Pitch Day & Award",
    workshopNum: "9",
    date: "MAR 16 2025",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
    topic1: "TBD",
  },
];
